// bonemap.ts file
export const BONE_MAP: Record<string, string> = {
    Hips: 'J_Bip_C_Hips', Spine: 'J_Bip_C_Spine', Spine1: 'J_Bip_C_Chest',
    Spine2: 'J_Bip_C_UpperChest', Neck: 'J_Bip_C_Neck', Head: 'J_Bip_C_Head',
    hips: 'J_Bip_C_Hips', spine: 'J_Bip_C_Spine', chest: 'J_Bip_C_Chest',
    upperChest: 'J_Bip_C_UpperChest', neck: 'J_Bip_C_Neck', head: 'J_Bip_C_Head',
    jaw: 'J_Bip_C_Head', leftEye: 'J_Adj_L_FaceEye', rightEye: 'J_Adj_R_FaceEye',
    LeftShoulder: 'J_Bip_L_Shoulder', LeftArm: 'J_Bip_L_UpperArm',
    LeftForeArm: 'J_Bip_L_LowerArm', LeftHand: 'J_Bip_L_Hand',
    leftShoulder: 'J_Bip_L_Shoulder', leftUpperArm: 'J_Bip_L_UpperArm',
    leftLowerArm: 'J_Bip_L_LowerArm', leftHand: 'J_Bip_L_Hand',
    RightShoulder: 'J_Bip_R_Shoulder', RightArm: 'J_Bip_R_UpperArm',
    RightForeArm: 'J_Bip_R_LowerArm', RightHand: 'J_Bip_R_Hand',
    rightShoulder: 'J_Bip_R_Shoulder', rightUpperArm: 'J_Bip_R_UpperArm',
    rightLowerArm: 'J_Bip_R_LowerArm', rightHand: 'J_Bip_R_Hand',
    LeftUpLeg: 'J_Bip_L_UpperLeg', LeftLeg: 'J_Bip_L_LowerLeg',
    LeftFoot: 'J_Bip_L_Foot', LeftToeBase: 'J_Bip_L_ToeBase',
    leftUpperLeg: 'J_Bip_L_UpperLeg', leftLowerLeg: 'J_Bip_L_LowerLeg',
    leftFoot: 'J_Bip_L_Foot', leftToes: 'J_Bip_L_ToeBase',
    RightUpLeg: 'J_Bip_R_UpperLeg', RightLeg: 'J_Bip_R_LowerLeg',
    RightFoot: 'J_Bip_R_Foot', RightToeBase: 'J_Bip_R_ToeBase',
    rightUpperLeg: 'J_Bip_R_UpperLeg', rightLowerLeg: 'J_Bip_R_LowerLeg',
    rightFoot: 'J_Bip_R_Foot', rightToes: 'J_Bip_R_ToeBase',
    LeftHandThumb1: 'J_Bip_L_Thumb1', LeftHandThumb2: 'J_Bip_L_Thumb2', LeftHandThumb3: 'J_Bip_L_Thumb3',
    LeftHandIndex1: 'J_Bip_L_Index1', LeftHandIndex2: 'J_Bip_L_Index2', LeftHandIndex3: 'J_Bip_L_Index3',
    LeftHandMiddle1: 'J_Bip_L_Middle1', LeftHandMiddle2: 'J_Bip_L_Middle2', LeftHandMiddle3: 'J_Bip_L_Middle3',
    LeftHandRing1: 'J_Bip_L_Ring1', LeftHandRing2: 'J_Bip_L_Ring2', LeftHandRing3: 'J_Bip_L_Ring3',
    LeftHandPinky1: 'J_Bip_L_Little1', LeftHandPinky2: 'J_Bip_L_Little2', LeftHandPinky3: 'J_Bip_L_Little3',
    leftThumbMetacarpal: 'J_Bip_L_Thumb1', leftThumbProximal: 'J_Bip_L_Thumb2', leftThumbDistal: 'J_Bip_L_Thumb3',
    leftIndexProximal: 'J_Bip_L_Index1', leftIndexIntermediate: 'J_Bip_L_Index2', leftIndexDistal: 'J_Bip_L_Index3',
    leftMiddleProximal: 'J_Bip_L_Middle1', leftMiddleIntermediate: 'J_Bip_L_Middle2', leftMiddleDistal: 'J_Bip_L_Middle3',
    leftRingProximal: 'J_Bip_L_Ring1', leftRingIntermediate: 'J_Bip_L_Ring2', leftRingDistal: 'J_Bip_L_Ring3',
    leftLittleProximal: 'J_Bip_L_Little1', leftLittleIntermediate: 'J_Bip_L_Little2', leftLittleDistal: 'J_Bip_L_Little3',
    RightHandThumb1: 'J_Bip_R_Thumb1', RightHandThumb2: 'J_Bip_R_Thumb2', RightHandThumb3: 'J_Bip_R_Thumb3',
    RightHandIndex1: 'J_Bip_R_Index1', RightHandIndex2: 'J_Bip_R_Index2', RightHandIndex3: 'J_Bip_R_Index3',
    RightHandMiddle1: 'J_Bip_R_Middle1', RightHandMiddle2: 'J_Bip_R_Middle2', RightHandMiddle3: 'J_Bip_R_Middle3',
    RightHandRing1: 'J_Bip_R_Ring1', RightHandRing2: 'J_Bip_R_Ring2', RightHandRing3: 'J_Bip_R_Ring3',
    RightHandPinky1: 'J_Bip_R_Little1', RightHandPinky2: 'J_Bip_R_Little2', RightHandPinky3: 'J_Bip_R_Little3',
    rightThumbMetacarpal: 'J_Bip_R_Thumb1', rightThumbProximal: 'J_Bip_R_Thumb2', rightThumbDistal: 'J_Bip_R_Thumb3',
    rightIndexProximal: 'J_Bip_R_Index1', rightIndexIntermediate: 'J_Bip_R_Index2', rightIndexDistal: 'J_Bip_R_Index3',
    rightMiddleProximal: 'J_Bip_R_Middle1', rightMiddleIntermediate: 'J_Bip_R_Middle2', rightMiddleDistal: 'J_Bip_R_Middle3',
    rightRingProximal: 'J_Bip_R_Ring1', rightRingIntermediate: 'J_Bip_R_Ring2', rightRingDistal: 'J_Bip_R_Ring3',
    rightLittleProximal: 'J_Bip_R_Little1', rightLittleIntermediate: 'J_Bip_R_Little2', rightLittleDistal: 'J_Bip_R_Little3',
}
